### ISSUE TITLE
`ellipsis` prop doesn't work if `resizeOnReflow` is set to `true`

### ISSUE THREAD

**Issue by 07akioni** [chenquincy/react-ellipsis#16]
https://codesandbox.io/s/ancient-darkness-c9xfc?file=/src/App.tsx:0-609

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/144396879-4ab28bfd-a46a-40bc-8391-2365149ce267.png)

实际用起来成了这种效果

**Comment by chenquincy** [comment]
@07akioni sandbox 的案例看起来没有问题呀。

**Comment by chenquincy** [comment]
@07akioni It's a bug obviously. I will fix it later.

**Comment by chenquincy** [comment]
@07akioni Fix in v1.1.4.

**Comment by 07akioni** [comment]
https://github.com/chenquincy/react-ellipsis/commit/1e85c7436a4b0f1cc77cf73788bab556b58fffeb#r61241844

**Comment by 07akioni** [comment]
@chenquincy 有空的话看一下我的 comment

**Comment by chenquincy** [comment]
@07akioni Fix with your another issue. Close the issue if it work well.

**Comment by 07akioni** [comment]
https://codesandbox.io/s/ancient-darkness-c9xfc?file=/src/App.tsx

在多个 ellipsis 同时存在时会出问题，不知道是不是监听有点问题

@chenquincy

**Comment by chenquincy** [comment]
@07akioni 试试 1.1.8

**Comment by 07akioni** [comment]
成了
