### ISSUE TITLE
`resizeOnReflow` prop won't work after `ellipsis` is toggled once

### ISSUE THREAD

**Issue by 07akioni** [chenquincy/react-ellipsis#17]
Set `ellipsis` to `false` then `true` and resize the frame.

https://codesandbox.io/s/ancient-darkness-c9xfc?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/18677354/144983402-6089cec7-e6a0-4790-84fd-d3efa7a149de.png)

**Comment by 07akioni** [comment]
Any progress?

**Comment by chenquincy** [comment]
@07akioni Sorry for later. I'm working very busy for a close project that let me missed the message. It will be fixed later.

**Comment by chenquincy** [comment]
@07akioni Fix at v1.1.5

**Comment by 07akioni** [comment]
> @07akioni Sorry for later. I'm working very busy for a close project that let me missed the message. It will be fixed later.

No need for sorry, thanks for fixing it.

**Comment by 07akioni** [comment]
@chenquincy Still doesn't work.

触发了一次 ellipsis 之后就不能 work 了。

![image](https://user-images.githubusercontent.com/18677354/145750437-ec011f1e-2046-49e4-9da1-ac7cde742efe.png)

**Comment by chenquincy** [comment]
@07akioni 我发布前忘记 build 了。。加班加傻了。。

**Comment by chenquincy** [comment]
我走一下 action 上的发布吧

**Comment by eyea** [comment]
> 我走一下 action 上的发布吧

hhhh 还是得自动化，不然真的容易忘 :)
