### ISSUE TITLE
在antd的select的option中使用无效

### ISSUE THREAD

**Issue by MrSteins** [chenquincy/react-ellipsis#18]
antd的select里使用要把display：-webkit-box给disabled掉才能截断，不知道什么原因

**Comment by ruofee** [comment]
> antd的select里使用要把display：-webkit-box给disabled掉才能截断，不知道什么原因

@MrSteins 我在 select 没发现你说的属性呀，能否给个截图

**Comment by chenquincy** [comment]
未复现，无响应

**Comment by MrSteins** [comment]
@ruofee 
<img width="427" alt="截屏2022-07-19 上午10 11 14" src="https://user-images.githubusercontent.com/66707682/179649579-678be8bc-23bf-4ee0-8d77-bb1f9fc36429.png">
![截屏2022-07-19 上午10 11 36](https://user-images.githubusercontent.com/66707682/179649633-0bb64db5-39ae-4cc7-b78a-3575c324545f.png)
![截屏2022-07-19 上午10 12 50](https://user-images.githubusercontent.com/66707682/179649717-49cefea3-0992-4be8-b19f-bb27068bec7f.png)

**Comment by canvascat** [comment]
原因在于继承了父元素的 `white-space: nowrap;`

```jsx
const App = () => (<div style={{ width: 400, whiteSpace: 'nowrap' }}>
  <Ellipsis ellipsis  text="高性能、可自定义的 react 文本缩略组件。支持自定义缩略符、html 自定义缩略符、尾字符过滤、缩略回调等功能。" maxLine={1} />
</div>)
```
