### ISSUE TITLE
useLayoutEffect warning when using with Next.js

### ISSUE THREAD

**Issue by quyctd** [chenquincy/react-ellipsis#19]
Hi, thank you for this great library.

When integrating react-ellipsis with a Nextjs project, I see this issue in the server log:

>Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

Could you fix it using something like `useisomorphiclayouteffect`. Thank you.

**Comment by chenquincy** [comment]
@quyctd Thx for report. Fixed at 1.10.0.

**Comment by quyctd** [comment]
@chenquincy Thank you, it's work 🚀
