### ISSUE TITLE
small initial text

### ISSUE THREAD

**Issue by meeshh** [chenquincy/react-ellipsis#21]
If text property is a string that is less than maxLine, the ellipsisNode still shows. The maxLine prop should be static in my useCase but the text is dynamic.
Image attached

```javascript
<Ellipsis
      text='My short text'
      ellipsis={ellipsisState}
      maxLine={3}
      reflowOnResize
      onEllipsisClick={toggleReadMore}
      ellipsisNode={<strong> ...{ellipsisState ? t('readMore') : t('readLess')}</strong>}
      endExcludes={[' ', ',', '.']}
/>
```

<img width="430" alt="image" src="https://user-images.githubusercontent.com/620224/197170867-ae1d64f7-43b5-4051-88ab-b571e87cb163.png">

**Comment by meeshh** [comment]
Solved with the `onReflow` callback. But isn't it better if it works out of the box?
Thanks

**Comment by chenquincy** [comment]
@meeshh I can't reproduce your issue, can you just reproduce it on an online code website such as [codepen](https://codepen.io/) and share the case to me?
