### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by bffisher** [chenquincy/react-ellipsis#22]
https://github.com/chenquincy/react-ellipsis/blob/f820a395ace8d643e63f755ec19157de7b9a83f1/src/utils/is.ts#L11

在我的项目初始化时，由于一些特殊的操作，document.body会为null。

**Comment by ruofee** [comment]
可以在 document.body 设置回原始值的时候再渲染 react-ellipsis 组件
