### ISSUE TITLE
使用ellipsisNode这个属性就会报错

### ISSUE THREAD

**Issue by datoou** [chenquincy/react-ellipsis#23]
![image](https://github.com/chenquincy/react-ellipsis/assets/52907799/bdc6ae11-2e92-49be-af90-e1d22609c6d4)

**Comment by chenquincy** [comment]
@datoou 我这没有复现出来，能贴一下使用的代码吗？

**Comment by datoou** [comment]
> @datoou 我这没有复现出来，能贴一下使用的代码吗？

重启了下项目就好了
