### ISSUE TITLE
[BUG] 富文本模式下，部分场景截取存在问题

### ISSUE THREAD

**Issue by ruofee** [chenquincy/react-ellipsis#24]
More details：https://github.com/ruofee/vue-ellipsis-component/issues/16#issuecomment-2251791002

**Comment by ruofee** [comment]
Fix: https://github.com/chenquincy/react-ellipsis/commit/5d8e452feb67bc5169a9b81d8de031c2eb3dad2d

**Comment by Panjun-520** [comment]
这个我下新版本就ok了吧

**Comment by ruofee** [comment]
是的

**Comment by Panjun-520** [comment]
1.2.0-alpha.0,这个版本是测试版吗

**Comment by ruofee** [comment]
最新的版本应该是 [1.1.11](https://www.npmjs.com/package/react-ellipsis-component/v/1.1.11) @Panjun-520

**Comment by Panjun-520** [comment]
ok，你们在处理html文本时直接用了dangerouslySetInnerHTML，还是用了其他的库吗

**Comment by ruofee** [comment]
就是 innerHTML，具体可以查看文档：http://react-ellipsis.quincychen.cn/zh/api#%E5%B1%9E%E6%80%A7，需要预防 XSS 攻击可以自行做处理。
