### ISSUE TITLE
在手机上切换ellipsis时，文字出现不连续现象，发生抖动，影响体验

### ISSUE THREAD

**Issue by biology-w** [chenquincy/react-ellipsis#5]
1，直接在手机浏览器中测试，切换ellipsis时，先展示ellipsisNode，不展示其他文字。（pc上Chrome是好的，没有这种现象）
如图：
![image](https://user-images.githubusercontent.com/25600705/114996555-857f5480-9ed1-11eb-9d67-3a71d2733d26.png)

https://user-images.githubusercontent.com/25600705/114996414-64b6ff00-9ed1-11eb-9b45-267e43626a97.mp4

![image](https://user-images.githubusercontent.com/25600705/114996331-4f41d500-9ed1-11eb-9247-89e054504bf4.png)

**Comment by biology-w** [comment]
![image](https://user-images.githubusercontent.com/25600705/115002704-a5197b80-9ed7-11eb-8c2b-ce96a505eb5b.png)
可能是这部分导致的，很突兀导致容器高度没有了。然后高度一点一点增加的，直到目标高度。
建议：这里能使用二分查找方法优化嘛？  然后高度是一点一点减少到目标值的。就不会出现上面情况了。

**Comment by ruofee** [comment]
@biology-w 确实存在这个问题, 是因为修改`ellipsis`这个属性时`react-ellipsis-component`内部有一个切换组件的动作;

我们会尽快调整`react-ellipsis-component`组件内部逻辑 (^ _ ^)

**Comment by chenquincy** [comment]
@biology-w 问题已在 v1.0.0 版本中修复（如测试后无问题请关闭下 issue）。感谢反馈~

**Comment by biology-w** [comment]
谢谢了！
