### ISSUE TITLE
部分浏览器中文缩略显示异常

### ISSUE THREAD

**Issue by 07akioni** [chenquincy/react-ellipsis#7]
https://react-ellipsis.quincychen.cn/zh/start

![image](https://user-images.githubusercontent.com/18677354/134656151-79212e9d-7674-493a-8722-be98165af82b.png)

😂

**Comment by chenquincy** [comment]
@07akioni 可能是缓存问题？试试打开控制台刷新看看，之前的版本有问题。

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/134656496-d0312e32-e792-4e7b-ae9e-fc2b7f615564.png)

线上有问题，而且我本地中文也有点问题

**Comment by chenquincy** [comment]
问题的原因是不同浏览器对于行高的处理不兼容，大多数默认行高是 font-size，有些浏览器则是 font-size*1.1，解决方法也很简单，给容器设置一个 line-height 就可以解决

**Comment by chenquincy** [comment]
有部分浏览器的行高会大于 font-size*1.1，此时就会出现这种情况。因为不想做过多的兼容去破坏默认行为，所以没有内置的设置一个 line-height，我在文档添加一个 tip 做提醒吧。

**Comment by chenquincy** [comment]
文档上的问题已经修复了，顺便在开始使用中加了 tips
