### ISSUE TITLE
折叠的行数和显示的行数分开

### ISSUE THREAD

**Issue by 07akioni** [chenquincy/react-ellipsis#8]
产品提了个需求，要求超过 5 行折叠成 3 行，这个好弄么

**Comment by chenquincy** [comment]
@07akioni emmm   实现倒是可以实现，但是我建议和产品 argue 一下。。

**Comment by 07akioni** [comment]
> @07akioni 实现确实没啥难度，但是我觉得从用户体验上说根本没什么差异。 如果引入这个支持的话，从属性上需要添加 visibleLine 和 visibleHeight 来适配，并且会提高使用者的理解成本。 如果需要的话，我可以给你提供一个 beta 版本，但在正式版本上出于个人的坚持，我不打算引入这个功能。

我是不想 fork 来解决这个问题，有没有更优雅点的方式

**Comment by chenquincy** [comment]
使用无问题的话关闭下 issue

**Comment by 07akioni** [comment]
![Uploading image.png…]()
奇怪了

**Comment by chenquincy** [comment]
咦   这么神奇

**Comment by chenquincy** [comment]
![image](https://user-images.githubusercontent.com/10976378/136888981-ed552c89-4649-4fe4-99b3-8c4928a28492.png)
昨天上传有收到成功邮件

**Comment by chenquincy** [comment]
![image](https://user-images.githubusercontent.com/10976378/136889571-39c8b846-1bd2-48cc-b465-b69e7277d027.png)
之前使用 github action 自动发的，看 log 没问题，刚刚手动试了下发现版本已存在。我先发个 fix 版本给你用，然后发邮件给 npm 看看。

**Comment by 07akioni** [comment]
雀食，不老靠谱的
