### ISSUE TITLE
查看更多永远展示在右边

### ISSUE THREAD

**Issue by cwjTerrace** [chenquincy/react-ellipsis#9]
![image](https://user-images.githubusercontent.com/29698222/138387850-5e9616ea-8e99-440b-8549-06985b74d917.png)
这个效果能实现吗？不管几行查看更多永远在右边（多行右下角）

**Comment by chenquincy** [comment]
@cwjTerrace ellipsisNode 设置为一个带右 padding 的 '...'，自行实现一个 absolute 定位在容器右下角的 ”详情 >“，默认隐藏，onReflow 中判断是否展示 "详情 >"。

**Comment by chenquincy** [comment]
长时间无反馈，先关闭 issue。有需要另开。
